service: ${self:provider.environment.SLSCONF_SERVICE_NAME}

provider:
  name: aws
  environment:
    SLSCONF_STAGE: ${env:SLSCONF_STAGE, 'v0'}
    SLSCONF_SERVICE_NAME: ${env:SLSCONF_SERVICE_NAME, 'slsconf-matching-app'}
    SLSCONF_REGION: ${env:SLSCONF_REGION, 'ap-northeast-1'}
  runtime: nodejs6.10
  stage: ${self:provider.environment.SLSCONF_STAGE}
  region: ${self:provider.environment.SLSCONF_REGION}

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

package:
  include:
    - package.json
    - src/**
  exclude:
    - .git/**
    - sandbox/**

functions:
  index:
    handler: src/index.handler
    events:
      - http:
          path: /
          method: get
  signup:
    handler: src/auth.signup
    events:
      - http:
          path: signup
          method: get
  activation:
    handler: src/auth.activation
    events:
      - http:
          path: activation
          method: get
  login:
    handler: src/auth.login
    events:
      - http:
          path: login
          method: get
  mypage:
    handler: src/mypage.handler
    events:
      - http:
          path: mypage
          method: get
  me:
    handler: src/me.handler
    events:
      - http:
          path: me
          method: get
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:ap-northeast-1:079973668103:userpool/ap-northeast-1_bKLNdEwKU

#    Define function environment variables here
#    environment:
#      variable2: value2

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
